name: Beta News Mr Green
favicon: null
layout_spectrum: 0.5910555638838559
typography_spectrum: 0.6632612561807036
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6283325562253594
  lightness: 0.9077572438400239
  saturation: 0.8217190762516111
  rhythmicContrast: 0.7947833528742194
purpose: []
