name: Beta News Mr Green
favicon: null
layout_spectrum: 0.74097
typography_spectrum: 0.61629
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c3c4bf'
    - '#004506'
    - '#7f8325'
    - '#525b1a'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
